markdown: rdiscount
pygments: true
encoding: utf-8

title: HJKing
description: "Personal website for HJKing, an ASIC engineer in Wuhan, China."

url: http://hjking.github.io

permalink: /blog/:year/:month/:day/:title

author:
    name: HJKing
    username: hjking
    email: hon9jin@gmail.com
    github: hjking
    twitter: hon9jin
    facebook: kin9hom
    linkedin: kinghom
    gravatar: http://www.gravatar.com/avatar/f5f95a698d284cdb1acece79504077db.png

paginate: 7

blog:
    cover: true

comments:
    provider: disqus
    disqus:
        short_name: hjking
    uyan:

analytics:
    provider: google
    google:
        tracking_id: 'UA-6627086-2'
        domain: 'hjking.github.io'
    baidu:
        site_id :


about_path: /pages/about.html
tags_path: /pages/tags.html
categories_path: /pages/categories.html
archive_path: /pages/all_archives.html
category: category

links:
    github: https://github.com/hjking
    bitbucket: https://www.bitbucket.org/kinghom
    blog: http://hjking.github.io
    blog_repo: https://github.com/hjking/hjking.github.com
    blog_zip: https://github.com/hjking/hjking.github.com/archive/master.zip
    feedback: https://github.com/hjking/hjking.github.com/issues/new
    bootstrap: http://getbootstrap.com
    jekyll: http://jekyllrb.com
    github_pages: https://pages.github.com

# Settings for sharing
# Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
# Add a tweet button        => provider : tweet
# Add a like button         => provider : like (you also need a facebook appid)
# Add a plus one button     => provider : plusone
# Add a HN button       => provider : hn
# Add them all (i.e. hn + tweet + plusone + like) => provider : all
# Set 'provider' to the sharing provider you want to use.
# Set 'provider' to false to turn sharing off globally.
#
sharing :
    provider : jiathis
    twitter :
        size :
        via :
        count :
    facebook :
        appid : 123
        layout : button_count
        font :
        faces : false
        width : 90
    googleplus :
        size : medium
        width :
        annotation : bubble
    linkedin :
        counter : right
    jiathis:
        user_id : 1887218
    baidu:

sociallink:
  - title: LinkedIn
    href: http://www.linkedin.com/in/kinghom
    class: fa fa-linkedin-square
  - title: GitHub
    href: https://github.com/hjking
    class: fa fa-github-square
  - title: Bitbucket
    href: https://www.bitbucket.org/kinghom
    class: fa fa-bitbucket-square
  - title: Stack Overflow
    href: http://stackoverflow.com/users/1605724/hjking
    class: fa fa-stack-overflow
  - title: Facebook
    href: https://www.facebook.com/kin9hom
    class: fa fa-facebook-square
  - title: Twitter
    href: https://twitter.com/hon9jin
    class: fa fa-twitter-square
  - title: Google+
    href: https://plus.google.com/103205960311343871154/posts
    class: fa fa-google-plus-square
  - title: Instagram
    href: http://instagram.com/kinghom
    class: fa fa-instagram
  - title: Flickr
    href: http://www.flickr.com/photos/kinghom
    class: fa fa-flickr
  - title: Foursquare
    href: https://foursquare.com/kinghom
    class: fa fa-foursquare
  - title: Weibo
    href: http://weibo.com/hon9jin
    class: fa fa-weibo
  - title: Renren
    href: http://www.renren.com/200047031/profile
    class: fa fa-renren
  - title: LastFM
    href: http://www.last.fm/user/KingHom
    class: fa fa-music
  - title: Tumblr
    href: http://kinghom.tumblr.com
    class: fa fa-tumblr-square
  - title: 500px
    href: http://500px.com/hjking
    class: fa fa-picture-o

# Custom vars
cover:      /assets/img/cover.jpg
